package br.com.trixti.itm.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ItmBoleto generated by hbm2java
 */
@Entity
@Table(name = "itm_contrato_notificacao", schema = "public")
public class ContratoNotificacao implements java.io.Serializable {

	private static final long serialVersionUID = 1376759741243805368L;

	@Id
	@SequenceGenerator(name="CONTRATO_NOTIFICACAO_ID_GENERATOR", sequenceName="itm_contrato_notificacao_id_seq", allocationSize = 1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="CONTRATO_NOTIFICACAO_ID_GENERATOR") 
	@Column(name = "id", unique = true, nullable = false) 
	private Integer id;
	
	@Enumerated(EnumType.STRING)
	private TipoContratoNotificacao tipo;
	
	
	private String texto;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_envio", length = 29)
	private Date dataEnvio;
	
	@ManyToOne
	@JoinColumn(name="id_contrato")
	private Contrato contrato;
	
	@Enumerated(EnumType.STRING)
	@Column(name="meio_envio")
	private MeioEnvioContratoNotificacao meioEnvio;
	

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TipoContratoNotificacao getTipo() {
		return tipo;
	}

	public void setTipo(TipoContratoNotificacao tipo) {
		this.tipo = tipo;
	}

	public String getTexto() {
		return texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	public Date getDataEnvio() {
		return dataEnvio;
	}

	public void setDataEnvio(Date dataEnvio) {
		this.dataEnvio = dataEnvio;
	}

	public Contrato getContrato() {
		return contrato;
	}

	public void setContrato(Contrato contrato) {
		this.contrato = contrato;
	}

	public MeioEnvioContratoNotificacao getMeioEnvio() {
		return meioEnvio;
	}

	public void setMeioEnvio(MeioEnvioContratoNotificacao meioEnvio) {
		this.meioEnvio = meioEnvio;
	}
	
	
	

}
