package br.com.trixti.itm.entity;
// default package
// Generated 22/02/2017 14:34:07 by Hibernate Tools 4.3.4.Final

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ItmEquipamento generated by hbm2java
 */
@Entity
@Table(name = "itm_equipamento", schema = "public")
public class Equipamento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2127519180048329065L;

	@Id
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	private String nome;
	
	private String marca;
	
	private String modelo;
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "equipamento")
	private List<ContratoEquipamento> contratoEquipamentos;

	public Equipamento() {
	}

	public Equipamento(Integer id) {
		this.id = id;
	}

	
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	
	public List<ContratoEquipamento> getContratoEquipamentos() {
		return this.contratoEquipamentos;
	}

	public void setContratoEquipamentos(List<ContratoEquipamento> contratoEquipamentos) {
		this.contratoEquipamentos = contratoEquipamentos;
	}

	public String getMarca() {
		return marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	public String getModelo() {
		return modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

}
