package br.com.trixti.itm.entity;
// default package
// Generated 22/02/2017 14:34:07 by Hibernate Tools 4.3.4.Final

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Nas generated by hbm2java
 */
@Entity
@Table(name = "grupo_parametro", schema = "public")
public class GrupoParametro implements java.io.Serializable {

	private static final long serialVersionUID = 7544569728250822318L;

	@Id
	@SequenceGenerator(name="GRUPO_PARAMETRO_ID_GENERATOR", sequenceName="itm_cliente_id_seq", allocationSize = 1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="GRUPO_PARAMETRO_ID_GENERATOR") 
	private Integer id;	
	
	
	@ManyToOne
	@JoinColumn(name="id_grupo")
	private Grupo grupo;
	
	private String propriedade;
	private String operador;
	private String valor;
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public Grupo getGrupo() {
		return grupo;
	}
	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}
	public String getPropriedade() {
		return propriedade;
	}
	public void setPropriedade(String propriedade) {
		this.propriedade = propriedade;
	}
	public String getOperador() {
		return operador;
	}
	public void setOperador(String operador) {
		this.operador = operador;
	}
	public String getValor() {
		return valor;
	}
	public void setValor(String valor) {
		this.valor = valor;
	}
	
	
}
