package br.com.trixti.itm.entity;
// default package
// Generated 22/02/2017 14:34:07 by Hibernate Tools 4.3.4.Final

import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ItmGrupo generated by hbm2java
 */
@Entity
@Table(name = "itm_grupo", schema = "public")
public class Grupo implements java.io.Serializable {

	private static final long serialVersionUID = -8140969307057217925L;

	@Id
	@SequenceGenerator(name="GRUPO_ID_GENERATOR", sequenceName="itm_cliente_id_seq", allocationSize = 1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="GRUPO_ID_GENERATOR") 
	private Integer id;
	
	private String nome;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grupo")
	private List<ContratoGrupo> contratoGrupos;
	
	@OneToMany(mappedBy="grupo",cascade=CascadeType.ALL,orphanRemoval=true)
	private List<GrupoParametro> grupoParametros;

	public Grupo() {
	}

	public Grupo(Integer id) {
		this.id = id;
	}


	
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	
	public List<ContratoGrupo> getContratoGrupos() {
		return this.contratoGrupos;
	}

	public void setItmContratoGrupos(List<ContratoGrupo> contratoGrupos) {
		this.contratoGrupos = contratoGrupos;
	}

	public List<GrupoParametro> getGrupoParametros() {
		return grupoParametros;
	}

	public void setGrupoParametros(List<GrupoParametro> grupoParametros) {
		this.grupoParametros = grupoParametros;
	}

	public void setContratoGrupos(List<ContratoGrupo> contratoGrupos) {
		this.contratoGrupos = contratoGrupos;
	}

}
