package br.com.trixti.itm.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ItmLog generated by hbm2java
 */
@Entity
@Table(name = "itm_log", schema = "public")
public class Log implements java.io.Serializable {

	private static final long serialVersionUID = 22775385501094990L;
	
	@Id
	@SequenceGenerator(name="LOG_ID_GENERATOR", sequenceName="itm_log_id_seq", allocationSize = 1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="LOG_ID_GENERATOR") 
	private Integer id;
	
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_log", length = 29)
	private Date dataLog;
	
	private String login;
	
	@Enumerated(EnumType.STRING)
	private TipoLog tipo;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getDataLog() {
		return dataLog;
	}

	public void setDataLog(Date dataLog) {
		this.dataLog = dataLog;
	}

	public String getLogin() {
		return login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public TipoLog getTipo() {
		return tipo;
	}

	public void setTipo(TipoLog tipo) {
		this.tipo = tipo;
	}
	
	
	

}
