package br.com.trixti.itm.entity;
// default package
// Generated 22/02/2017 14:34:07 by Hibernate Tools 4.3.4.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;

/**
 * ItmUsuario generated by hbm2java
 */
@Audited
@Entity
@Table(name = "itm_movimentacao_financeira", schema = "public")
@AuditTable(value="itm_movimentacao_financeira_historico")
public class MovimentacaoFinanceira implements java.io.Serializable {

	private static final long serialVersionUID = 22775385501094990L;
	
	@Id
	@SequenceGenerator(name="MOVIMENTACAO_FINANCEIRA_ID_GENERATOR", sequenceName="itm_movimentacao_financeira_id_seq", allocationSize = 1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="MOVIMENTACAO_FINANCEIRA_ID_GENERATOR") 
	private Integer id;
	
	private String nome;
	
	private BigDecimal valor;
	
	@NotAudited
	@ManyToOne
	@JoinColumn(name="id_centro_custo")
	private CentroCusto centroCusto;
	
	@Temporal(TemporalType.TIMESTAMP)
	private Date data;
	
	@Enumerated(EnumType.STRING)
	private TipoMovimentacaoFinanceira tipo;
	
	@NotAudited
	@ManyToOne
	@JoinColumn(name="id_arquivo_sici")
	private ArquivoSici arquivoSici;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public BigDecimal getValor() {
		return valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	public CentroCusto getCentroCusto() {
		return centroCusto;
	}

	public void setCentroCusto(CentroCusto centroCusto) {
		this.centroCusto = centroCusto;
	}

	public Date getData() {
		return data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	public TipoMovimentacaoFinanceira getTipo() {
		return tipo;
	}

	public void setTipo(TipoMovimentacaoFinanceira tipo) {
		this.tipo = tipo;
	}

	public ArquivoSici getArquivoSici() {
		return arquivoSici;
	}

	public void setArquivoSici(ArquivoSici arquivoSici) {
		this.arquivoSici = arquivoSici;
	}
	

}
