package br.com.trixti.itm.entity;
// default package
// Generated 22/02/2017 14:34:07 by Hibernate Tools 4.3.4.Final

import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ItmNotificacao generated by hbm2java
 */
@Entity
@Table(name = "itm_notificacao", schema = "public")
public class Notificacao implements java.io.Serializable {

	private static final long serialVersionUID = 22775385501094990L;
	
	@Id
	@SequenceGenerator(name="NOTIFICACAO_ID_GENERATOR", sequenceName="itm_notificacao_id_seq", allocationSize = 1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="NOTIFICACAO_ID_GENERATOR") 
	private Integer id;
	
	private String nome;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_inicio", length = 29)
	private Date dataInicio;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_fim", length = 29)
	private Date dataFim;
	
	private String mensagem;

	@OneToMany(mappedBy="notificacao",cascade=CascadeType.ALL,orphanRemoval=true)
	private List<NotificacaoTag> tags;

	public Integer getId() {
		return id;
	}


	public void setId(Integer id) {
		this.id = id;
	}


	public String getNome() {
		return nome;
	}


	public void setNome(String nome) {
		this.nome = nome;
	}


	public Date getDataInicio() {
		return dataInicio;
	}


	public void setDataInicio(Date dataInicio) {
		this.dataInicio = dataInicio;
	}


	public Date getDataFim() {
		return dataFim;
	}


	public void setDataFim(Date dataFim) {
		this.dataFim = dataFim;
	}


	public String getMensagem() {
		return mensagem;
	}


	public void setMensagem(String mensagem) {
		this.mensagem = mensagem;
	}


	public List<NotificacaoTag> getTags() {
		return tags;
	}


	public void setTags(List<NotificacaoTag> tags) {
		this.tags = tags;
	}
	

	

}
