package br.com.trixti.itm.entity;
// default package
// Generated 22/02/2017 14:34:07 by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ItmParametro generated by hbm2java
 */
@Entity
@Table(name = "itm_parametro", schema = "public")
public class Parametro implements java.io.Serializable {


	private static final long serialVersionUID = 8924539309625088184L;

	@Id
	@SequenceGenerator(name="PARAMETRO_ID_GENERATOR", sequenceName="itm_parametro_id_seq", allocationSize = 1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="PARAMETRO_ID_GENERATOR") 
	@Column(name = "id", unique = true, nullable = false) 
	private Integer id;
	
	@Column(name="nome_empresa")
	private String nomeEmpresa;

	private String cnpj;
	
	@Column(name="qtd_dias_desbloqueio_temporario")
	private Integer qtdDiasDesbloqueioTemporario;
	
	
	@Column(name="qtd_dias_bloqueio")
	private Integer qtdDiasBloqueio;
	
	
	@Column(name="qtd_dias_aviso")
	private Integer qtdDiasAviso;
	
	
	@Column(name="qtd_dias_inativacao")
	private Integer qtdDiasInativacao;
	
	@Column(name="logradouro")
	private String logradouro;

	@Column(name="bairro")
	private String bairro;

	@Column(name="cep")
	private String cep;

	@Column(name="cidade")
	private String cidade;

	@Column(name="uf")
	private String uf;
	
	
	

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNomeEmpresa() {
		return nomeEmpresa;
	}

	public void setNomeEmpresa(String nomeEmpresa) {
		this.nomeEmpresa = nomeEmpresa;
	}

	public String getCnpj() {
		return cnpj;
	}

	public void setCnpj(String cnpj) {
		this.cnpj = cnpj;
	}

	public Integer getQtdDiasDesbloqueioTemporario() {
		return qtdDiasDesbloqueioTemporario;
	}

	public void setQtdDiasDesbloqueioTemporario(Integer qtdDiasDesbloqueioTemporario) {
		this.qtdDiasDesbloqueioTemporario = qtdDiasDesbloqueioTemporario;
	}

	public Integer getQtdDiasBloqueio() {
		return qtdDiasBloqueio;
	}

	public void setQtdDiasBloqueio(Integer qtdDiasBloqueio) {
		this.qtdDiasBloqueio = qtdDiasBloqueio;
	}

	public Integer getQtdDiasAviso() {
		return qtdDiasAviso;
	}

	public void setQtdDiasAviso(Integer qtdDiasAviso) {
		this.qtdDiasAviso = qtdDiasAviso;
	}

	public Integer getQtdDiasInativacao() {
		return qtdDiasInativacao;
	}

	public void setQtdDiasInativacao(Integer qtdDiasInativacao) {
		this.qtdDiasInativacao = qtdDiasInativacao;
	}

	public String getLogradouro() {
		return logradouro;
	}

	public void setLogradouro(String logradouro) {
		this.logradouro = logradouro;
	}

	public String getBairro() {
		return bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	public String getCep() {
		return cep;
	}

	public void setCep(String cep) {
		this.cep = cep;
	}

	public String getCidade() {
		return cidade;
	}

	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	public String getUf() {
		return uf;
	}

	public void setUf(String uf) {
		this.uf = uf;
	}
	

	
	
}
