package br.com.trixti.itm.entity;
// default package
// Generated 22/02/2017 14:34:07 by Hibernate Tools 4.3.4.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ItmProduto generated by hbm2java
 */
@Entity
@Table(name = "itm_produto", schema = "public")
public class Produto implements java.io.Serializable {

	private static final long serialVersionUID = 22775385501094990L;
	
	@Id
	@SequenceGenerator(name="PRODUTO_ID_GENERATOR", sequenceName="itm_produto_id_seq", allocationSize = 1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="PRODUTO_ID_GENERATOR") 
	private Integer id;
	
	
	private String nome;
	
	@Enumerated(EnumType.STRING)
	private TipoProduto tipo;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_inicio", length = 29)
	private Date dataInicio;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_fim", length = 29)
	private Date dataFim;
	
	private BigDecimal valor;
	
	private Integer upload;
	private Integer download;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produto")
	private Set<ContratoProduto> contratoProdutos = new HashSet<ContratoProduto>(0);
	
	@ManyToOne
	@JoinColumn(name="id_servico")
	private Servico servico;
	
	private boolean dedicado;

	public Produto() {
	}

	public Produto(Integer id) {
		this.id = id;
	}

	public Produto(Integer id, String nome, TipoProduto tipo, Date dataInicio, Date dataFim,
			Set<ContratoProduto> contratoProdutos) {
		this.id = id;
		this.nome = nome;
		this.tipo = tipo;
		this.dataInicio = dataInicio;
		this.dataFim = dataFim;
		this.contratoProdutos = contratoProdutos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public TipoProduto getTipo() {
		return this.tipo;
	}

	public void setTipo(TipoProduto tipo) {
		this.tipo = tipo;
	}

	
	public Date getDataInicio() {
		return this.dataInicio;
	}

	public void setDataInicio(Date dataInicio) {
		this.dataInicio = dataInicio;
	}

	
	public Date getDataFim() {
		return this.dataFim;
	}

	public void setDataFim(Date dataFim) {
		this.dataFim = dataFim;
	}

	
	public Set<ContratoProduto> getContratoProdutos() {
		return this.contratoProdutos;
	}

	public void setContratoProdutos(Set<ContratoProduto> contratoProdutos) {
		this.contratoProdutos = contratoProdutos;
	}

	public BigDecimal getValor() {
		return valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	public Integer getUpload() {
		return upload;
	}

	public void setUpload(Integer upload) {
		this.upload = upload;
	}

	public Integer getDownload() {
		return download;
	}

	public void setDownload(Integer download) {
		this.download = download;
	}

	public Servico getServico() {
		return servico;
	}

	public void setServico(Servico servico) {
		this.servico = servico;
	}

	public boolean isDedicado() {
		return dedicado;
	}

	public void setDedicado(boolean dedicado) {
		this.dedicado = dedicado;
	}
	

}
