package br.com.trixti.itm.entity;
// default package
// Generated 22/02/2017 14:34:07 by Hibernate Tools 4.3.4.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ItmProduto generated by hbm2java
 */
@Entity
@Table(name = "itm_produto", schema = "public")
public class Produto implements java.io.Serializable {

	private static final long serialVersionUID = 22775385501094990L;
	private Integer id;
	private String nome;
	private String tipo;
	private Date dataInicio;
	private Date dataFim;
	
	private BigDecimal valor;
	
	private Set<ClienteProduto> clienteProdutos = new HashSet<ClienteProduto>(0);

	public Produto() {
	}

	public Produto(Integer id) {
		this.id = id;
	}

	public Produto(Integer id, String nome, String tipo, Date dataInicio, Date dataFim,
			Set<ClienteProduto> clienteProdutos) {
		this.id = id;
		this.nome = nome;
		this.tipo = tipo;
		this.dataInicio = dataInicio;
		this.dataFim = dataFim;
		this.clienteProdutos = clienteProdutos;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nome")
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "tipo")
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_inicio", length = 29)
	public Date getDataInicio() {
		return this.dataInicio;
	}

	public void setDataInicio(Date dataInicio) {
		this.dataInicio = dataInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_fim", length = 29)
	public Date getDataFim() {
		return this.dataFim;
	}

	public void setDataFim(Date dataFim) {
		this.dataFim = dataFim;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produto")
	public Set<ClienteProduto> getClienteProdutos() {
		return this.clienteProdutos;
	}

	public void setClienteProdutos(Set<ClienteProduto> clienteProdutos) {
		this.clienteProdutos = clienteProdutos;
	}

	public BigDecimal getValor() {
		return valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

}
