package br.com.trixti.itm.entity;
// default package
// Generated 22/02/2017 14:34:07 by Hibernate Tools 4.3.4.Final

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Radacct generated by hbm2java
 */
@Entity
@Table(name = "radacct", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "acctuniqueid"))
public class Radacct implements java.io.Serializable {

	private long radacctid;
	private String acctsessionid;
	private String acctuniqueid;
	private String username;
	private String groupname;
	private String realm;
	private Serializable nasipaddress;
	private String nasportid;
	private String nasporttype;
	private Date acctstarttime;
	private Date acctupdatetime;
	private Date acctstoptime;
	private Long acctinterval;
	private Long acctsessiontime;
	private String acctauthentic;
	private String connectinfoStart;
	private String connectinfoStop;
	private Long acctinputoctets;
	private Long acctoutputoctets;
	private String calledstationid;
	private String callingstationid;
	private String acctterminatecause;
	private String servicetype;
	private String framedprotocol;
	private Serializable framedipaddress;

	public Radacct() {
	}

	public Radacct(long radacctid, String acctsessionid, String acctuniqueid, Serializable nasipaddress) {
		this.radacctid = radacctid;
		this.acctsessionid = acctsessionid;
		this.acctuniqueid = acctuniqueid;
		this.nasipaddress = nasipaddress;
	}

	public Radacct(long radacctid, String acctsessionid, String acctuniqueid, String username, String groupname,
			String realm, Serializable nasipaddress, String nasportid, String nasporttype, Date acctstarttime,
			Date acctupdatetime, Date acctstoptime, Long acctinterval, Long acctsessiontime, String acctauthentic,
			String connectinfoStart, String connectinfoStop, Long acctinputoctets, Long acctoutputoctets,
			String calledstationid, String callingstationid, String acctterminatecause, String servicetype,
			String framedprotocol, Serializable framedipaddress) {
		this.radacctid = radacctid;
		this.acctsessionid = acctsessionid;
		this.acctuniqueid = acctuniqueid;
		this.username = username;
		this.groupname = groupname;
		this.realm = realm;
		this.nasipaddress = nasipaddress;
		this.nasportid = nasportid;
		this.nasporttype = nasporttype;
		this.acctstarttime = acctstarttime;
		this.acctupdatetime = acctupdatetime;
		this.acctstoptime = acctstoptime;
		this.acctinterval = acctinterval;
		this.acctsessiontime = acctsessiontime;
		this.acctauthentic = acctauthentic;
		this.connectinfoStart = connectinfoStart;
		this.connectinfoStop = connectinfoStop;
		this.acctinputoctets = acctinputoctets;
		this.acctoutputoctets = acctoutputoctets;
		this.calledstationid = calledstationid;
		this.callingstationid = callingstationid;
		this.acctterminatecause = acctterminatecause;
		this.servicetype = servicetype;
		this.framedprotocol = framedprotocol;
		this.framedipaddress = framedipaddress;
	}

	@Id

	@Column(name = "radacctid", unique = true, nullable = false)
	public long getRadacctid() {
		return this.radacctid;
	}

	public void setRadacctid(long radacctid) {
		this.radacctid = radacctid;
	}

	@Column(name = "acctsessionid", nullable = false)
	public String getAcctsessionid() {
		return this.acctsessionid;
	}

	public void setAcctsessionid(String acctsessionid) {
		this.acctsessionid = acctsessionid;
	}

	@Column(name = "acctuniqueid", unique = true, nullable = false)
	public String getAcctuniqueid() {
		return this.acctuniqueid;
	}

	public void setAcctuniqueid(String acctuniqueid) {
		this.acctuniqueid = acctuniqueid;
	}

	@Column(name = "username")
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "groupname")
	public String getGroupname() {
		return this.groupname;
	}

	public void setGroupname(String groupname) {
		this.groupname = groupname;
	}

	@Column(name = "realm")
	public String getRealm() {
		return this.realm;
	}

	public void setRealm(String realm) {
		this.realm = realm;
	}

	@Column(name = "nasipaddress", nullable = false)
	public Serializable getNasipaddress() {
		return this.nasipaddress;
	}

	public void setNasipaddress(Serializable nasipaddress) {
		this.nasipaddress = nasipaddress;
	}

	@Column(name = "nasportid")
	public String getNasportid() {
		return this.nasportid;
	}

	public void setNasportid(String nasportid) {
		this.nasportid = nasportid;
	}

	@Column(name = "nasporttype")
	public String getNasporttype() {
		return this.nasporttype;
	}

	public void setNasporttype(String nasporttype) {
		this.nasporttype = nasporttype;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "acctstarttime", length = 35)
	public Date getAcctstarttime() {
		return this.acctstarttime;
	}

	public void setAcctstarttime(Date acctstarttime) {
		this.acctstarttime = acctstarttime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "acctupdatetime", length = 35)
	public Date getAcctupdatetime() {
		return this.acctupdatetime;
	}

	public void setAcctupdatetime(Date acctupdatetime) {
		this.acctupdatetime = acctupdatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "acctstoptime", length = 35)
	public Date getAcctstoptime() {
		return this.acctstoptime;
	}

	public void setAcctstoptime(Date acctstoptime) {
		this.acctstoptime = acctstoptime;
	}

	@Column(name = "acctinterval")
	public Long getAcctinterval() {
		return this.acctinterval;
	}

	public void setAcctinterval(Long acctinterval) {
		this.acctinterval = acctinterval;
	}

	@Column(name = "acctsessiontime")
	public Long getAcctsessiontime() {
		return this.acctsessiontime;
	}

	public void setAcctsessiontime(Long acctsessiontime) {
		this.acctsessiontime = acctsessiontime;
	}

	@Column(name = "acctauthentic")
	public String getAcctauthentic() {
		return this.acctauthentic;
	}

	public void setAcctauthentic(String acctauthentic) {
		this.acctauthentic = acctauthentic;
	}

	@Column(name = "connectinfo_start")
	public String getConnectinfoStart() {
		return this.connectinfoStart;
	}

	public void setConnectinfoStart(String connectinfoStart) {
		this.connectinfoStart = connectinfoStart;
	}

	@Column(name = "connectinfo_stop")
	public String getConnectinfoStop() {
		return this.connectinfoStop;
	}

	public void setConnectinfoStop(String connectinfoStop) {
		this.connectinfoStop = connectinfoStop;
	}

	@Column(name = "acctinputoctets")
	public Long getAcctinputoctets() {
		return this.acctinputoctets;
	}

	public void setAcctinputoctets(Long acctinputoctets) {
		this.acctinputoctets = acctinputoctets;
	}

	@Column(name = "acctoutputoctets")
	public Long getAcctoutputoctets() {
		return this.acctoutputoctets;
	}

	public void setAcctoutputoctets(Long acctoutputoctets) {
		this.acctoutputoctets = acctoutputoctets;
	}

	@Column(name = "calledstationid")
	public String getCalledstationid() {
		return this.calledstationid;
	}

	public void setCalledstationid(String calledstationid) {
		this.calledstationid = calledstationid;
	}

	@Column(name = "callingstationid")
	public String getCallingstationid() {
		return this.callingstationid;
	}

	public void setCallingstationid(String callingstationid) {
		this.callingstationid = callingstationid;
	}

	@Column(name = "acctterminatecause")
	public String getAcctterminatecause() {
		return this.acctterminatecause;
	}

	public void setAcctterminatecause(String acctterminatecause) {
		this.acctterminatecause = acctterminatecause;
	}

	@Column(name = "servicetype")
	public String getServicetype() {
		return this.servicetype;
	}

	public void setServicetype(String servicetype) {
		this.servicetype = servicetype;
	}

	@Column(name = "framedprotocol")
	public String getFramedprotocol() {
		return this.framedprotocol;
	}

	public void setFramedprotocol(String framedprotocol) {
		this.framedprotocol = framedprotocol;
	}

	@Column(name = "framedipaddress")
	public Serializable getFramedipaddress() {
		return this.framedipaddress;
	}

	public void setFramedipaddress(Serializable framedipaddress) {
		this.framedipaddress = framedipaddress;
	}

}
