package br.com.trixti.itm.entity;
// default package
// Generated 22/02/2017 14:34:07 by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Radgroupcheck generated by hbm2java
 */
@Entity
@Table(name = "radgroupcheck", schema = "public")
public class Radgroupcheck implements java.io.Serializable {

	private int id;
	private String groupname;
	private String attribute;
	private String op;
	private String value;

	public Radgroupcheck() {
	}

	public Radgroupcheck(int id, String groupname, String attribute, String op, String value) {
		this.id = id;
		this.groupname = groupname;
		this.attribute = attribute;
		this.op = op;
		this.value = value;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "groupname", nullable = false)
	public String getGroupname() {
		return this.groupname;
	}

	public void setGroupname(String groupname) {
		this.groupname = groupname;
	}

	@Column(name = "attribute", nullable = false)
	public String getAttribute() {
		return this.attribute;
	}

	public void setAttribute(String attribute) {
		this.attribute = attribute;
	}

	@Column(name = "op", nullable = false, length = 2)
	public String getOp() {
		return this.op;
	}

	public void setOp(String op) {
		this.op = op;
	}

	@Column(name = "value", nullable = false)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
