package br.com.trixti.itm.entity;
// default package
// Generated 22/02/2017 14:34:07 by Hibernate Tools 4.3.4.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Radpostauth generated by hbm2java
 */
@Entity
@Table(name = "radpostauth", schema = "public")
public class Radpostauth implements java.io.Serializable {

	private long id;
	private String username;
	private String pass;
	private String reply;
	private String calledstationid;
	private String callingstationid;
	private Date authdate;

	public Radpostauth() {
	}

	public Radpostauth(long id, String username, Date authdate) {
		this.id = id;
		this.username = username;
		this.authdate = authdate;
	}

	public Radpostauth(long id, String username, String pass, String reply, String calledstationid,
			String callingstationid, Date authdate) {
		this.id = id;
		this.username = username;
		this.pass = pass;
		this.reply = reply;
		this.calledstationid = calledstationid;
		this.callingstationid = callingstationid;
		this.authdate = authdate;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "username", nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "pass")
	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	@Column(name = "reply")
	public String getReply() {
		return this.reply;
	}

	public void setReply(String reply) {
		this.reply = reply;
	}

	@Column(name = "calledstationid")
	public String getCalledstationid() {
		return this.calledstationid;
	}

	public void setCalledstationid(String calledstationid) {
		this.calledstationid = calledstationid;
	}

	@Column(name = "callingstationid")
	public String getCallingstationid() {
		return this.callingstationid;
	}

	public void setCallingstationid(String callingstationid) {
		this.callingstationid = callingstationid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "authdate", nullable = false, length = 35)
	public Date getAuthdate() {
		return this.authdate;
	}

	public void setAuthdate(Date authdate) {
		this.authdate = authdate;
	}

}
