package br.com.trixti.itm.entity;
// default package
// Generated 22/02/2017 14:34:07 by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Radreply generated by hbm2java
 */
@Entity
@Table(name = "radreply", schema = "public")
public class Radreply implements java.io.Serializable {

	private static final long serialVersionUID = 8690099000547410454L;
	
	@Id
	@Column(name = "id", unique = true, nullable = false)
	@SequenceGenerator(name="RADREPLY_ID_GENERATOR", sequenceName="radreply_id_seq", allocationSize = 1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="RADREPLY_ID_GENERATOR") 
	private int id;
	private String username;
	private String attribute;
	private String op;
	private String value;

	public Radreply() {
	}

	public Radreply(int id, String username, String attribute, String op, String value) {
		this.id = id;
		this.username = username;
		this.attribute = attribute;
		this.op = op;
		this.value = value;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "username", nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "attribute", nullable = false)
	public String getAttribute() {
		return this.attribute;
	}

	public void setAttribute(String attribute) {
		this.attribute = attribute;
	}

	@Column(name = "op", nullable = false, length = 2)
	public String getOp() {
		return this.op;
	}

	public void setOp(String op) {
		this.op = op;
	}

	@Column(name = "value", nullable = false)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
