package br.com.trixti.itm.entity;
// default package
// Generated 22/02/2017 14:34:07 by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Radusergroup generated by hbm2java
 */
@Entity
@Table(name = "radusergroup", schema = "public")
public class Radusergroup implements java.io.Serializable {

	
	private static final long serialVersionUID = 8942643426660241498L;

	@Id
	@SequenceGenerator(name="RADUSERGROUP_ID_GENERATOR", sequenceName="radusergroup_id_seq", allocationSize = 1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="RADUSERGROUP_ID_GENERATOR") 
	@Column(name = "id", unique = true, nullable = false) 
	private int id;
	
	private String username;
	private String groupname;
	private int priority;

	public Radusergroup() {
	}

	public Radusergroup(int id, String username, String groupname, int priority) {
		this.id = id;
		this.username = username;
		this.groupname = groupname;
		this.priority = priority;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "username", nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "groupname", nullable = false)
	public String getGroupname() {
		return this.groupname;
	}

	public void setGroupname(String groupname) {
		this.groupname = groupname;
	}

	@Column(name = "priority", nullable = false)
	public int getPriority() {
		return this.priority;
	}

	public void setPriority(int priority) {
		this.priority = priority;
	}

}
