package br.com.trixti.itm.entity;
// default package
// Generated 22/02/2017 14:34:07 by Hibernate Tools 4.3.4.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import br.com.trixti.itm.to.PeriodoTO;

/**
 * ItmRetorno generated by hbm2java
 */

@Entity
@Table(name = "itm_retorno", schema = "public")
public class Retorno implements java.io.Serializable {

	private static final long serialVersionUID = 8924539309625088184L;

	@Id
	@SequenceGenerator(name="RETORNO_ID_GENERATOR", sequenceName="itm_retorno_id_seq", allocationSize = 1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="RETORNO_ID_GENERATOR") 
	@Column(name = "id", unique = true, nullable = false) 
	private Integer id;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_criacao")
	private Date dataCriacao;
	
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_processamento")
	private Date dataProcessamento;
	
	private String arquivo;
	
	private String banco;
	
	@Column(name="nome_arquivo")
	private String nomeArquivo;
	
	
	@Enumerated(EnumType.STRING)
	private StatusRetorno status;
	
	private String mensagem;
	
	@Transient
	private PeriodoTO periodoTO;
	 
	public Retorno(){
	}
	
	//return getManager().createQuery(criteria.multiselect(root.get("id"),root.get("dataCriacao"),root.get("banco"),root.get("dataProcessamento"),root.get("nomeArquivo"))
	
	public Retorno(Integer id,Date dataCriacao,String banco,Date dataProcessamento,String nomeArquivo,StatusRetorno status,String mensagem){
		setId(id);
		setDataCriacao(dataCriacao);
		setBanco(banco);
		setDataProcessamento(dataProcessamento);
		setNomeArquivo(nomeArquivo);
		setStatus(status);
		setMensagem(mensagem);
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getDataCriacao() {
		return dataCriacao;
	}

	public void setDataCriacao(Date dataCriacao) {
		this.dataCriacao = dataCriacao;
	}

	public Date getDataProcessamento() {
		return dataProcessamento;
	}

	public void setDataProcessamento(Date dataProcessamento) {
		this.dataProcessamento = dataProcessamento;
	}

	public String getArquivo() {
		return arquivo;
	}

	public void setArquivo(String arquivo) {
		this.arquivo = arquivo;
	}

	public String getBanco() {
		return banco;
	}

	public void setBanco(String banco) {
		this.banco = banco;
	}

	public String getNomeArquivo() {
		return nomeArquivo;
	}

	public void setNomeArquivo(String nomeArquivo) {
		this.nomeArquivo = nomeArquivo;
	}

	public StatusRetorno getStatus() {
		return status;
	}

	public void setStatus(StatusRetorno status) {
		this.status = status;
	}

	public String getMensagem() {
		return mensagem;
	}

	public void setMensagem(String mensagem) {
		this.mensagem = mensagem;
	}

	public PeriodoTO getPeriodoTO() {
		if (periodoTO == null) {
			periodoTO = new PeriodoTO();
		}
		return periodoTO;
	}

	public void setPeriodoTO(PeriodoTO periodoTO) {
		this.periodoTO = periodoTO;
	}
	
	

}
