package br.com.trixti.itm.entity;
// default package
// Generated 22/02/2017 14:34:07 by Hibernate Tools 4.3.4.Final

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ItmServico generated by hbm2java
 */
@Entity
@Table(name = "itm_servico_local", schema = "public")
public class ServicoLocal implements java.io.Serializable {

	private static final long serialVersionUID = 22775385501094990L;
	
	@Id
	@SequenceGenerator(name="SERVICO_LOCAL_ID_GENERATOR", sequenceName="itm_servico_local_id_seq", allocationSize = 1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SERVICO_LOCAL_ID_GENERATOR") 
	private Integer id;
	
	@ManyToOne
	@JoinColumn(name="id_servico")
	private Servico servico;
	
	@ManyToOne
	@JoinColumn(name="uf")
	private Uf uf;
	
	@ManyToOne
	@JoinColumn(name="id_cidade")
	private Cidade cidade;
	
	private boolean sede;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Servico getServico() {
		return servico;
	}

	public void setServico(Servico servico) {
		this.servico = servico;
	}

	public Uf getUf() {
		return uf;
	}

	public void setUf(Uf uf) {
		this.uf = uf;
	}

	public Cidade getCidade() {
		return cidade;
	}

	public void setCidade(Cidade cidade) {
		this.cidade = cidade;
	}

	public boolean isSede() {
		return sede;
	}

	public void setSede(boolean sede) {
		this.sede = sede;
	}

}
