package br.com.trixti.itm.entity;
// default package
// Generated 22/02/2017 14:34:07 by Hibernate Tools 4.3.4.Final

import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ItmServico generated by hbm2java
 */
@Entity
@Table(name = "itm_servico", schema = "public")
public class Servico implements java.io.Serializable {

	private static final long serialVersionUID = 22775385501094990L;
	
	@Id
	@SequenceGenerator(name="SERVICO_ID_GENERATOR", sequenceName="itm_servico_id_seq", allocationSize = 1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SERVICO_ID_GENERATOR") 
	private Integer id;
	
	private String fistel;
	
	@Enumerated(EnumType.STRING)
	private TipoServico tipo;
	
	@OneToMany(mappedBy="servico",cascade=CascadeType.ALL,orphanRemoval=true)
	private List<ServicoLocal> locais;
	

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFistel() {
		return fistel;
	}

	public void setFistel(String fistel) {
		this.fistel = fistel;
	}

	public TipoServico getTipo() {
		return tipo;
	}

	public void setTipo(TipoServico tipo) {
		this.tipo = tipo;
	}

	public List<ServicoLocal> getLocais() {
		return locais;
	}

	public void setLocais(List<ServicoLocal> locais) {
		this.locais = locais;
	}
	

}
