package br.com.trixti.itm.entity;
// default package
// Generated 22/02/2017 14:34:07 by Hibernate Tools 4.3.4.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import br.com.trixti.itm.enums.PerfilEnum;

/**
 * ItmUsuario generated by hbm2java
 */
@Entity
@Table(name = "itm_usuario", schema = "public")
public class Usuario implements java.io.Serializable {

	private static final long serialVersionUID = 22775385501094990L;
	
	@Id
	@SequenceGenerator(name="USUARIO_ID_GENERATOR", sequenceName="itm_usuario_id_seq", allocationSize = 1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="USUARIO_ID_GENERATOR") 
	private Integer id;
	
	private String nome;
	
	@Enumerated(EnumType.STRING)
	private PerfilEnum perfil;
	
	private String login;
	
	private String senha;

	private String email;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="data_criacao")
	private Date dataCriacao;

	public Integer getId() {
		return id;
	}


	public void setId(Integer id) {
		this.id = id;
	}


	public String getNome() {
		return nome;
	}


	public void setNome(String nome) {
		this.nome = nome;
	}


	public PerfilEnum getPerfil() {
		return perfil;
	}


	public void setPerfil(PerfilEnum perfil) {
		this.perfil = perfil;
	}


	public String getLogin() {
		return login;
	}


	public void setLogin(String login) {
		this.login = login;
	}


	public String getSenha() {
		return senha;
	}


	public void setSenha(String senha) {
		this.senha = senha;
	}


	public Date getDataCriacao() {
		return dataCriacao;
	}


	public void setDataCriacao(Date dataCriacao) {
		this.dataCriacao = dataCriacao;
	}


	public String getEmail() {
		return email;
	}


	public void setEmail(String email) {
		this.email = email;
	}
	
	
	
	

}
